all:
  hosts:
    master:
      ansible_host: 13.66.26.152
  children:
    k8s:
      hosts:
        master:
          ansible_host: 13.66.26.152             
        worker1:
          ansible_host: 13.66.31.170
        worker2:
          ansible_host: 157.55.177.75
    masters:
      hosts:
        master:
          ansible_host: 13.66.26.152        
    workers:
      hosts:
        worker1:
          ansible_host: 13.66.31.170
        worker2:
          ansible_host: 157.55.177.75
    nfss:
      hosts:
        nfs:
          ansible_host: 13.66.31.181