---

- hosts: all
  gather_facts: false
  tasks:

    # 1 - Cambiar la Zona Horaria a Bogota - Colombia
    - name: Cambiar la Zona Horaria a America - Bogota
      command: sudo timedatectl set-timezone America/Bogota
      delegate_to: 127.0.0.1

    # 2 - Instalar chrony
    - name: Instalando Chrony
      command: sudo dnf install chrony -y
      delegate_to: 127.0.0.1      

    # 3 - Habilitar chrony
    - name: Habilitar Chrony
      command: sudo systemctl enable chronyd
      delegate_to: 127.0.0.1      

    # 4 - Iniciar chrony
    - name: Iniciando chrony
      command: sudo systemctl start chronyd
      delegate_to: 127.0.0.1      

    # 5 - Activar la sincronizacion
    - name: Iniciando chrony
      command:timedatectl set-ntp true
      delegate_to: 127.0.0.1      

