all:
  hosts:
    master:
      ansible_host: 13.65.250.182  
  children:
    masters:
      hosts:
        master:
          ansible_host: 13.65.250.182        
    workers:
      hosts:
        worker1:
          ansible_host: 13.65.250.152
        worker2:
          ansible_host: 13.65.250.120
    nfss:
      hosts:
        nfs:
          ansible_host: 13.65.250.151