all:
  hosts:
    master:
      ansible_host: 23.102.184.69
  children:
    k8s:
      hosts:
        master:
          ansible_host: 23.102.184.69             
        worker1:
          ansible_host: 52.171.223.19
        worker2:
          ansible_host: 52.171.223.29  
    masters:
      hosts:
        master:
          ansible_host: 23.102.184.69        
    workers:
      hosts:
        worker1:
          ansible_host: 52.171.223.19
        worker2:
          ansible_host: 52.171.223.29
    nfss:
      hosts:
        nfs:
          ansible_host: 52.171.223.9
