all:
  hosts:
    master:
      ansible_host: 13.84.186.43
  children:
    k8s:
      hosts:
        master:
          ansible_host: 13.84.186.43             
        worker1:
          ansible_host: 13.85.19.118
        worker2:
          ansible_host: 157.55.84.145  
    masters:
      hosts:
        master:
          ansible_host: 13.84.186.43        
    workers:
      hosts:
        worker1:
          ansible_host: 13.85.19.118
        worker2:
          ansible_host: 157.55.84.145
    nfss:
      hosts:
        nfs:
          ansible_host: 23.102.152.73
