all:
  hosts:
    master:
      ansible_host: 104.214.99.6
  children:
    k8s:
      hosts:
        master:
          ansible_host: 104.214.99.6             
        worker1:
          ansible_host: 13.65.168.197
        worker2:
          ansible_host: 13.65.190.186
    masters:
      hosts:
        master:
          ansible_host: 104.214.99.6        
    workers:
      hosts:
        worker1:
          ansible_host: 13.65.168.197
        worker2:
          ansible_host: 13.65.190.186
    nfss:
      hosts:
        nfs:
          ansible_host: 13.65.185.165