all:
  hosts:
    master:
      ansible_host: 13.84.166.207
  children:
    k8s:
      hosts:
        master:
          ansible_host: 13.84.166.207             
        worker1:
          ansible_host: 13.65.211.102
        worker2:
          ansible_host: 13.65.211.120
    masters:
      hosts:
        master:
          ansible_host: 13.84.166.207        
    workers:
      hosts:
        worker1:
          ansible_host: 13.65.211.102
        worker2:
          ansible_host: 13.65.211.120
    nfss:
      hosts:
        nfs:
          ansible_host: 13.65.211.113