all:
  hosts:
    master:
      ansible_host: 13.66.4.7
    worker1:
      ansible_host: 13.66.4.31
  children:
    masters:
      hosts:
        master:
          ansible_host: 13.66.4.7        
    workers:
      hosts:
        worker1:
          ansible_host: 13.66.4.31
        worker2:
          ansible_host: 104.214.74.43
    nfss:
      hosts:
        nfs:
          ansible_host: 40.74.240.81