all:
  hosts:
    master:
      ansible_host: 23.102.130.182
    worker1:
      ansible_host: 70.37.56.62
  children:
    masters:
      hosts:
        master:
          ansible_host: 23.102.130.182        
    workers:
      hosts:
        worker1:
          ansible_host: 70.37.56.62
        worker2:
          ansible_host: 70.37.52.139
    nfss:
      hosts:
        nfs:
          ansible_host: 23.98.134.171