all:
  hosts:
    master:
      ansible_host: 23.102.180.138 
    worker1:
      ansible_host: 13.65.250.152
  children:
    masters:
      hosts:
        master:
          ansible_host: 23.102.180.138        
    workers:
      hosts:
        worker1:
          ansible_host: 23.102.180.47
        worker2:
          ansible_host: 13.65.250.120
    nfss:
      hosts:
        nfs:
          ansible_host: 23.102.160.88