all:
  hosts:
    master:
      ansible_host: 13.84.207.100
  children:
    k8s:
      hosts:
        master:
          ansible_host: 13.84.207.100             
        worker1:
          ansible_host: 13.66.7.66
        worker2:
          ansible_host: 23.100.121.147  
    masters:
      hosts:
        master:
          ansible_host: 13.84.207.100        
    workers:
      hosts:
        worker1:
          ansible_host: 13.66.7.66
        worker2:
          ansible_host: 23.100.121.147
    nfss:
      hosts:
        nfs:
          ansible_host: 23.100.121.50
