---


# 1 - Crear comando  de Join de nodos
- name: Crear comando  de Join de nodos 
  command: kubeadm token create --print-join-command
  register: local_command
  become: yes
  when: inventory_hostname in groups['masters']

# 2 - Mostrar comando  de Join de nodos
- name: Mostar Comando de Join
  debug:
    var: local_command.stdout_lines


# 3 - Ejecutar Join en nodos
- name: Ejecutar Join en nodos
  command: "{{local_command}}"
  become: yes
  when: inventory_hostname in groups['workers']


# 5 - Permitir el acceso de los contenedores a localhost
- name: Permitir el acceso de los contenedores a localhost
  command:  ip a
  become: yes
  when: inventory_hostname in groups['workers']
