---

# 1 - Crear el Directorio donde se almacenar치 la Informaci칩n del nfs
- name: Crear Directorio de nfs
  command: mkdir /mnt/srv
  become: yes


# 2 - Crear el Directorio donde se almacenar치 la Informaci칩n del nfs
- name: Dar permisos al usuairo local sobre el directorio
  command: chown -R ec2-user /mnt/srv/nfs
  become: yes

