apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  namespace: webapp-volumenes
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/srv/nfs
    server: 10.0.1.40